stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - echo "Création de l'environnement virtuel..."
    - python3 -m venv venv
    - source venv/bin/activate
    - echo "Installation de pygame..."
    - pip install pygame
  tags:
    - ubuntu

test_job:
  stage: test
  script:
    - echo "Vérification de la syntaxe Python..."
    - python3 -m py_compile 2048.py
  tags:
    - ubuntu
deploy_job:
  stage: deploy
  script:
    - echo "Deploying the application..."
    - # Les étapes de déploiement seront définies plus tard avec Ansible et Kube
    - echo "Deployment initiated."
  tags:
    - ubuntu
  only:
    - main # Déclencher le déploiement uniquement sur la branche main
